# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('project', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectinfo.Project')),
            ],
        ),
    ]
