# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectinfo', '0001_initial'),
        ('participantinfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_url', models.URLField(max_length=255, unique=True)),
                ('url', models.URLField(default='', max_length=255)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('projects', mptt.fields.TreeManyToManyField(blank=True, related_name='blogs', to='projectinfo.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('guid', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participantinfo.Participant')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bloginfo.Blog')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('blog', 'guid')]),
        ),
    ]
