# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantinfo', '__first__'),
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_address', models.EmailField(max_length=254, unique=True)),
                ('archive_url', models.CharField(max_length=10000)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlinfo.MailingList')),
                ('project', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectinfo.Project')),
            ],
            options={
                'ordering': ('project__name',),
                'verbose_name': 'Mailing List-Project relationship',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('subject', models.TextField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_posts', to='participantinfo.Participant')),
                ('mailing_lists', models.ManyToManyField(related_name='posts', to='mlinfo.MailingList')),
                ('references', models.ManyToManyField(related_name='_post_references_+', to='mlinfo.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mailinglistproject',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlinfo.Purpose'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='projects',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='mailing_lists', through='mlinfo.MailingListProject', to='projectinfo.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='mailinglistproject',
            unique_together=set([('project', 'mailing_list')]),
        ),
    ]
