#!/usr/bin/env python

# Copyright 2017 Red Hat, Inc.
# License: GPLv3 or any later version

import os
import sys
import logging

os.environ['DJANGO_SETTINGS_MODULE'] = 'healthmeter.settings'

sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'healthmeter'))

application_ = None

logging.basicConfig(stream=sys.stderr,
                    level=logging.INFO)
logger = logging.getLogger(__name__)


def prepare():
    virtenv = os.environ['APPDIR'] + '/virtenv/'
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(
        virtenv, 'lib/python2.6/site-packages')

    try:
        virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
        execfile(virtualenv, dict(__file__=virtualenv))
    except:
        logger.warn("Could not activate virtualenv %s", virtualenv,
                    exc_info=True)


def get_application():
    global application_
    if application_:
        return application_

    prepare()
    from django.core.handlers.wsgi import WSGIHandler
    application_ = WSGIHandler()

    return application_


def application(environ, start_response):
    env_whitelist = set(('APPDIR', 'BASEURL'))
    for k, v in environ.items():
        if k.startswith('OPENSHIFT_') or k in env_whitelist:
            os.environ[k] = v

    return get_application()(environ, start_response)
