# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localpart', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Email Domain',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='participantinfo.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='domainpart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='participantinfo.EmailDomain'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='participantinfo.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='participantname',
            unique_together=set([('name', 'participant')]),
        ),
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together=set([('localpart', 'domainpart')]),
        ),
    ]
