# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import healthmeter.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectinfo', '0001_initial'),
        ('participantinfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.CharField(max_length=20)),
                ('close_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('component', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Bug Namespace',
            },
        ),
        migrations.CreateModel(
            name='BugTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseurl', models.URLField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', healthmeter.fields.PlaintextPasswordField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bug Tracker',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('comment_id', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_comments', to='participantinfo.Participant')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='btinfo.Bug')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='bt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='btinfo.Type'),
        ),
        migrations.AddField(
            model_name='bugnamespace',
            name='bug_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='btinfo.BugTracker'),
        ),
        migrations.AddField(
            model_name='bugnamespace',
            name='projects',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='bug_trackers', to='projectinfo.Project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='btinfo.Severity'),
        ),
        migrations.AddField(
            model_name='bug',
            name='tracker_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='btinfo.BugNamespace'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('bug', 'comment_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bugnamespace',
            unique_together=set([('product', 'component', 'bug_tracker')]),
        ),
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together=set([('tracker_info', 'bug_id')]),
        ),
    ]
