# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:49
from __future__ import unicode_literals

from django.db import migrations
import healthmeter.fields


class Migration(migrations.Migration):

    dependencies = [
        ('btinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtracker',
            name='api_token',
            field=healthmeter.fields.PlaintextPasswordField(blank=True, max_length=255, null=True),
        ),
    ]
