# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectinfo', '0001_initial'),
        ('participantinfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('line_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'VCS commits',
                'verbose_name': 'VCS commit',
            },
        ),
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committer_ids', to='participantinfo.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000, unique=True)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('project', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projectinfo.Project')),
            ],
            options={
                'verbose_name_plural': 'VCS repositories',
                'verbose_name': 'VCS repository',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'VCS types',
                'verbose_name': 'VCS type',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='vcsinfo.Type'),
        ),
        migrations.AddField(
            model_name='committer',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committers', to='vcsinfo.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='vcsinfo.Committer'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='vcsinfo.Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='committer',
            unique_together=set([('userid', 'repository')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('repository', 'commit_id')]),
        ),
    ]
